### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cjgrondin**
added version header, data version 2.1

### CODE REVIEW

**Comment by cthoyt** [comment]
@cjgrondin these files have some strange (2) marks in them. Are they supposed to replace the original ones in the root of this repo?

**Comment by cjgrondin** [comment]
Yes, they were supposed to replace the original files in the root of this repo. Do you have further details about the strange marks (are you talking about the name of the file including the (2) or the actual code? obo or owl or both?)  I can restore branch if necessary.

**Comment by cthoyt** [comment]
I just meant that the filename doesn't make sense.

**Comment by cjgrondin** [comment]
Ok, I renamed the files to ExO.obo and ExO.owl and uploaded again. Hopefully that will eliminate any confusion.

**Comment by cthoyt** [comment]
That actually created more confusion. There are now 3 similarly named files in the root of the repository, two pairs of which only differ by capitalization variants. Suggestion:

1. Delete `exo (2).obo`, ``exo (2).owl`, `exo.obo`, and ``exo.owo`
2. Rename `ExO.obo` to `exo.obo` then `ExO.owl` to `exo.owl`.

If you're not comfortable with git/the github interface, I could send a PR to do this for you.

**Comment by cjgrondin** [comment]
I'm trying to learn Git, so I attempted to make the changes you suggested (probably could've done it with one PR, but it looks like it worked). Please let me know if you have additional suggestions. Thanks!

**Comment by cthoyt** [comment]
Git definitely has a learning curve. You'll get there! I'm not so great with it myself, and use the [GitHub Desktop](https://desktop.github.com/) GUI to help whenever I can - it might be useful for you too.

**Comment by cjgrondin** [comment]
Thanks for the tip! I'll check it out.

**Pull request merged**
