### PR TITLE
Update exo.owl

### PR DESCRIPTION
**Pull request by laurenechan**
Adding exposure stimulus term as a parent for exposure stimulus. Definition based on existing relationship term in RO: https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002309&viewMode=All&siblings=false

### CODE REVIEW

**Comment by matentzn** [comment]
You are editing the wrong ontology I think.. @cjgrondin can you make sure to point @laurenechan to the correct edit file?

**Comment by laurenechan** [comment]
Uh oh.. sorry about that @matentzn @cjgrondin ! I didn't see an exo-edit.owl file in the repo I cloned, did I just miss it?

**Comment by cjgrondin** [comment]
I usually update both files, exo.obo and exo.owl.

**Comment by cjgrondin** [comment]
For multiple edits, I update in protege and save in both owl and obo formats. For small edits, like a label change, I do it manually for both files.

**Pull request merged**
